name: Clang Format Checker
on: [push]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: giavancini/clang-format-github-action@v4
        with:
          style: llvm
          sources: "*.cpp,*.h"